# Generated by Django 4.2.30 on 2026-05-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_alter_ingredient_name_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert')], max_length=100),
        ),
    ]
