# Generated by Django 6.0.5 on 2026-05-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_alter_recipe_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
